Lesson 4. HW 4. Realization 4. Main task tests fixed + Optional Rule realized.
Meal: rewritten queries - сolumns query replaced by entire meal object query;
added @JoinColumn and @NotNull to user field;
JpaMealRepository: removed meal construction from Object[];
added setUser in save method;
MealService: LocalDate.MIN and MAX by custom values to avoid
org.hsqldb.HsqlException: data exception: datetime field overflow because of
 filtering with empty date fields;
MealTestData: in assertMatch methods condition for per field comparing
replaced by ignoring fields variant;
TestTimingRule replaced by TestStopwatchRule: for timing per test method and recording
method name and test time;